- hosts: localhost
  gather_facts: no
  vars:
    state: "present"
  tasks:
  - import_role:
      name: "opendatahub"
  - import_role:
      name: "aicoe-jupyterhub"
    when: odh_spec['aicoe-jupyterhub'] is defined and odh_spec['aicoe-jupyterhub']['odh_deploy']
  - import_role:
     name: "jupyter-on-openshift"
    when: odh_spec['jupyter-on-openshift'] is defined and odh_spec['jupyter-on-openshift']['odh_deploy']
  - import_role:
      name: "spark-operator"
    when: odh_spec['spark-operator'] is defined and odh_spec['spark-operator']['odh_deploy']
  - import_role:
      name: "prometheus"
    when: odh_spec['monitoring'] is defined and odh_spec['monitoring']['odh_deploy']
  - import_role:
      name: "grafana"
    when: odh_spec['monitoring'] is defined and odh_spec['monitoring']['odh_deploy']
  - import_role:    
      name: "seldon"
    when: odh_spec['seldon'] is defined and odh_spec['seldon']['odh_deploy']
