apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: opendatahubs.opendatahub.io
spec:
  group: opendatahub.io
  names:
    kind: OpenDataHub
    listKind: OpenDataHubList
    plural: opendatahubs
    singular: opendatahub
    shortNames:
    - odh
  scope: Namespaced
  version: v1alpha1
